version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      # Add test commands here if you have tests
      # - pytest
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app/**/*
    - requirements.txt
    - start.sh
    - .ebextensions/**/*
    - .platform/**/*
  discard-paths: no
